# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_en', models.TextField(blank=True, max_length=200, null=True, verbose_name='Ingl\xeas')),
                ('annotation_es_la', models.TextField(blank=True, max_length=200, null=True, verbose_name='Espanhol')),
                ('annotation_pt', models.TextField(blank=True, max_length=200, null=True, verbose_name='Portug\xeas')),
                ('annotation_es_sp', models.TextField(blank=True, max_length=200, null=True, verbose_name='Espanhol - Espanha')),
                ('annotation_fr', models.TextField(blank=True, max_length=200, null=True, verbose_name='Franc\xeas')),
            ],
            options={
                'verbose_name': 'Nota de Indexa\xe7\xe3o',
                'verbose_name_plural': 'Notas de Indexa\xe7\xe3o',
            },
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mesh', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID MESH')),
                ('id_decs', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID DeCS')),
                ('descriptor_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ingl\xeas')),
                ('descriptor_es_la', models.CharField(blank=True, max_length=200, null=True, verbose_name='Espanhol')),
                ('descriptor_pt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Portugu\xeas')),
                ('descriptor_es_sp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Espanhol - Espanha')),
                ('descriptor_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Franc\xeas')),
            ],
            options={
                'verbose_name': 'Descritor',
                'verbose_name_plural': 'Descritores',
            },
        ),
        migrations.CreateModel(
            name='ScopeNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_note_en', models.TextField(blank=True, max_length=200, null=True, verbose_name='Ingl\xeas')),
                ('scope_note_es_la', models.TextField(blank=True, max_length=200, null=True, verbose_name='Espanhol')),
                ('scope_note_pt', models.TextField(blank=True, max_length=200, null=True, verbose_name='Portugu\xeas')),
                ('scope_note_es_sp', models.TextField(blank=True, max_length=200, null=True, verbose_name='Espanhol')),
                ('scope_note_fr', models.TextField(blank=True, max_length=200, null=True, verbose_name='Franc\xeas')),
                ('id_scope_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Descritor.Descriptor')),
            ],
            options={
                'verbose_name': 'Defini\xe7\xe3o',
                'verbose_name_plural': 'Defini\xe7\xf5es',
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='id_annotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Descritor.Descriptor'),
        ),
    ]
